name: Build Python Module
description: Builds Python module and runs required checks
inputs:
  moduleName:
    required: true
    description: |
      The name of the module to be build.
      Does not include the full path, only the name.
  moduleFolder:
    required: true
    description: |
      The folder where the module resides. Uses empty string for root modules or the path
      from the root folder to the module folder otherwise.
    default: ""
runs:
  using: composite
  steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}
    - name: Load cached venv
      id: cached-poetry-dependencies
      uses: actions/cache@v3
      with:
        path: "${{ inputs.moduleFolder }}/.venv"
        key: venv-${{ runner.os }}-${{ env.PYTHON_VERSION }}--${{ hashFiles('poetry.lock') }}
        restore-keys: |
          venv-${{ runner.os }}-${{ env.PYTHON_VERSION }}-${{ hashFiles('poetry.lock') }}
          venv-${{ runner.os }}-${{ env.PYTHON_VERSION }}-
    - name: Setup poetry
      uses: abatilo/actions-poetry@v2.1.5
      with:
        poetry-version: ${{ env.POETRY_VERSION }}
    - name: Install dependencies
      shell: bash
      run: |
        poetry install
      working-directory: "${{ inputs.moduleFolder }}"
    - name: Run Black
      shell: bash
      run: |
        poetry run black . --check --diff --color
      working-directory: "${{ inputs.moduleFolder }}"
    - name: Run MyPy checks
      shell: bash
      run: |
        poetry run mypy -p autoxai --show-error-context --pretty --namespace-packages --explicit-package-bases
      working-directory: "${{ inputs.moduleFolder }}"
    - name: Run tests
      shell: bash
      run: poetry run pytest
      working-directory: "${{ inputs.moduleFolder }}"
