class Settings:
    experiment_label: str = "experiment_data"
    experiment_date_label: str = "experiment_date"
    hash_label: str = "experiment_hash"
    method_label: str = "experiment_method"
    stride_value: str = "stride_value"
    window_value: str = "window_value"
    target_class: str = "target_class"
    target_class_index: str = "target_class_index"
    hash_selectbox_key: str = "hash_selectbox"
    sample_name_key: str = "sample_name"
    epoch_number_key: str = "epoch_number"
    date_selectbox_key: str = "date_selectbox"
